### ISSUE TITLE
Add a sample testing model

### ISSUE THREAD

**Issue by lepisma** [Vernacular-ai/kaldi-serve#1]
@pskrunner14 do you have the smaller number model somewhere?

**Comment by pskrunner14** [comment]
> @pskrunner14 do you have the smaller number model somewhere?

Couldn't find it. Will train another and update asap

**Comment by lepisma** [comment]
better, try setting up a script to use aspire model from [here](https://kaldi-asr.org/models/m1)

**Comment by pskrunner14** [comment]
Added after edee65142fb6b732f172c17b66a08906a73f75a5
