### ISSUE TITLE
Word StartTime & EndTime should be changed by reference kaldi nnet3 code. 

### ISSUE THREAD

**Issue by kimkwangho82** [Vernacular-ai/kaldi-serve#10]
Thank you for your effort and achievement.
I have studied Kaldi (Speech-Recognition Tool) for years.

If you read the below Kaldi code, 
the word's start_time and end_time is not same between below code and 'decoder.hpp' code.

Kaldi code : https://github.com/kaldi-asr/kaldi/blob/master/src/online2bin/online2-tcp-nnet3-decode-faster.cc#L324

In 'decoder.hpp' code, 'frame_subsampling' is missed.
could you check the decoder's word's start_time and end_time.

Thank you.

**Comment by lepisma** [comment]
@pskrunner14 i am assuming you might have better view on this?

**Comment by pskrunner14** [comment]
Hi @kimkwangho82 thanks for pointing out the bug! It has been fixed in [v0.3.0](https://github.com/Vernacular-ai/kaldi-serve/releases/tag/0.3.0)
