### ISSUE TITLE
Components versions to build stable

### ISSUE THREAD

**Issue by kvishnivetsky** [Vernacular-ai/kaldi-serve#14]
Hi!

What versions of **Kaldi**, **Boost**, **GRPC** and **Google Protobuf** are recomended to buils latest (**0.4.0**) ?

**Comment by pskrunner14** [comment]
It should work with the latest versions of each, AFAIK we don't have any known issues with builds. Feel free to post here if you face any.

**Comment by pskrunner14** [comment]
closing this.
