### ISSUE TITLE
typo: not ./lib but ../lib in rpath

### ISSUE THREAD

**Issue by al-zatv** [Vernacular-ai/kaldi-serve#19]
in README, there is a line:

```
# Alternatively, you can also put all the required .so files in the ./lib/ directory since
# that is added to the binary's rpath.
```
it's a small typo, because ../lib is in rpath.

**Comment by pskrunner14** [comment]
Hi, this doesn't seem like a typo, `../lib` relative to the binary in `build/` would be in the current dir so `./lib` seems correct. Closing this.
