### ISSUE TITLE
[Question] Is there any guide about using Docker for this project?

### ISSUE THREAD

**Issue by ShahriyarR** [Vernacular-ai/kaldi-serve#22]
Hello,
I have noticed that there are Dockerfiles but could not find any direction about using Docker for this project.

**Comment by pskrunner14** [comment]
Hi, sorry we were busy with the move to library v1, you can now find the updated docker instructions for the gRPC server here: https://github.com/Vernacular-ai/kaldi-serve/tree/master/plugins/grpc#docker-image

**Comment by pskrunner14** [comment]
closing this.
