### ISSUE TITLE
Add support for  OGG_OPUS

### ISSUE THREAD

**Issue by seyuf** [Vernacular-ai/kaldi-serve#26]
Hi *,
Any plans for the *ogg_opus* encoding support?
I see some mentions [here](https://github.com/Vernacular-ai/kaldi-serve/blob/master/plugins/grpc/protos/kaldi_serve.proto) but it looks like the decoding is not implemented.
The functionality would be very helpful as the supported formats **wav** and **flac** are too heavy for one who'd like to support low latency transcription on devices with small bandwidth (mobile etc...)

I've already snooped around this [link](https://stackoverflow.com/questions/16496288/decoding-opus-audio-data) could be helpful.

Thanks for any feedback.

**Comment by lepisma** [comment]
@pskrunner14 do we want to support more formats? should we rely on an adaptor (outside of this project) instead?

**Comment by pskrunner14** [comment]
Currently seems best to keep outside the scope of this project but eventually, we do want to support other formats (would require more thought as we want to handle most of the common ones, not just the one referenced here).

For now @seyuf you could build a custom extension (plugin) around the library or add the decoder to the grpc plugin itself that handles the specific encoding you need. Feel free to post on this thread in case of any issues or help needed around the codebase.

**Comment by seyuf** [comment]
Hi @pskrunner14 @pskrunner14,
I have to say i was a bit confused by your comments at first the "**outside** of the project" part. I hadn't noticed,  you've totally changed the project's code base since the last time i've checked. 
After further review it seems, indeed, that the right course of action would be to add this functionality to grpc decoder. That being said, i wonder if keeping the grpc part as a simple plugin in this repo is the right? as **that** (grpc) was at the begin the  **main focus** of the project (I.e old repo description **gRPC server component for Kaldi based ASR**.). It is great that the focus has changed and all, but you should've created another repo or at least moved the grpc binding into a new repo IMHO. 
In any case thanks for all the work. 🙏
