### ISSUE TITLE
Words list is empty if using python bindings

### ISSUE THREAD

**Issue by farisalasmary** [Vernacular-ai/kaldi-serve#39]
Thank you very much for your great efforts!
I would like to ask about how can I get the list of words with the start time and end time for each word using the python bindings since it returns an empty list??

**Comment by pskrunner14** [comment]
You need to pass `word_level=True` arg in `get_decoded_results`. 

Reference: https://github.com/skit-ai/kaldi-serve/blob/master/python/kaldiserve_pybind/decoder.cpp#L79

**Comment by farisalasmary** [comment]
Thank you @pskrunner14 !! it worked!
